/// Flutter icons WeatherIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcons
///      fonts:
///       - asset: fonts/WeatherIcons.ttf
///
import 'package:flutter/widgets.dart';

class WeatherIconsData {
  WeatherIconsData._();

  static const _kFontFam = 'WeatherIcons';

  static const IconData cloud_rain3 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData cloud_snow = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cloud_thunder = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cloud_wind = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData cloudy = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData moon_cloud = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData moon_cloud_rain = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData moon_cloud_rain_thunder = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData moon_cloud_snow = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData moon_cloud_thunder = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData sun_cloud = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData sun_cloud_rain = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData cloud_rain_snow = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData cloud_rain_thunder = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData cloud_rain1 = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData cloud_rain2 = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData sun = const IconData(0xf111, fontFamily: _kFontFam);
}

class WeatherIcons {

  WeatherIcons._();

  static const Icon cloud_rain3 = const Icon(WeatherIconsData.cloud_rain3);
  static const Icon cloud_snow = const Icon(WeatherIconsData.cloud_snow);
  static const Icon cloud_thunder = const Icon(WeatherIconsData.cloud_thunder);
  static const Icon cloud_wind = const Icon(WeatherIconsData.cloud_wind);
  static const Icon cloudy = const Icon(WeatherIconsData.cloudy);
  static const Icon moon = const Icon(WeatherIconsData.moon);
  static const Icon moon_cloud = const Icon(WeatherIconsData.moon_cloud);
  static const Icon moon_cloud_rain = const Icon(WeatherIconsData.moon_cloud_rain);
  static const Icon moon_cloud_rain_thunder = const Icon(WeatherIconsData.moon_cloud_rain_thunder);
  static const Icon moon_cloud_snow = const Icon(WeatherIconsData.moon_cloud_snow);
  static const Icon moon_cloud_thunder = const Icon(WeatherIconsData.moon_cloud_thunder);
  static const Icon sun_cloud = const Icon(WeatherIconsData.sun_cloud);
  static const Icon sun_cloud_rain = const Icon(WeatherIconsData.sun_cloud_rain);
  static const Icon cloud_rain_snow = const Icon(WeatherIconsData.cloud_rain_snow);
  static const Icon cloud_rain_thunder = const Icon(WeatherIconsData.cloud_rain_thunder);
  static const Icon cloud_rain1 = const Icon(WeatherIconsData.cloud_rain1);
  static const Icon cloud_rain2 = const Icon(WeatherIconsData.cloud_rain2);
  static const Icon sun = const Icon(WeatherIconsData.sun, color: Color(0xFFF8B739), size: 200,);
}